- import_playbook: steps/01-Chrony_Setup.yml
- import_playbook: steps/02-OS_Packages_Install.yml
- import_playbook: steps/03-GHCup_Install.yml
- import_playbook: steps/04-libsodium_Install.yml
- import_playbook: steps/05-secp256k1_Install.yml
- import_playbook: steps/06-blst_Install.yml
- import_playbook: steps/07-Update_Env_File.yml
- import_playbook: steps/08-Install_Cardano_Node.yml