- name: Setup Cardano Node
  hosts: localhost
  become: yes
  vars_files:
    - install_param.yml

  tasks:
    - name: Remove libsodium-dev if present
      # To ensure that development headers for the libsodium cryptographic library are NOT install
      apt:
        name: libsodium-dev
        state: absent

    - name: Ensure working directory exists
      file:
        path: "{{ user_home }}/git"
        state: directory
        mode: '0755'

    - name: Clone cardano-node repository
      git:
        repo: https://github.com/IntersectMBO/cardano-node.git
        dest: "{{ user_home }}/git/cardano-node"
        clone: yes
        update: yes

    - name: Fetch all tags and submodules
      shell: git fetch --all --recurse-submodules --tags
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash

    - name: Show which release tag was checked out
      shell: |
        curl -s https://api.github.com/repos/IntersectMBO/cardano-node/releases/latest | jq -r .tag_name
      register: latest_cardano_tag
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash
        warn: false

    - name: Cabal update
      shell: export PATH="$PATH:{{ user_home }}/.ghcup/bin" && cabal update
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash
      become: false
      
    - name: Cabal build all
      shell: export PATH="$PATH:{{ user_home }}/.ghcup/bin" && cabal build all
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash
      become: false


    - name: Copy cardano-node binary to /usr/local/bin
      shell: cp -p "$(./scripts/bin-path.sh cardano-node)" /usr/local/bin/cardano-node
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash
      become: yes

    - name: Copy cardano-cli binary to /usr/local/bin
      shell: cp -p "$(./scripts/bin-path.sh cardano-cli)" /usr/local/bin/cardano-cli
      args:
        chdir: "{{ user_home }}/git/cardano-node"
        executable: /bin/bash
      become: yes

    - name: Show cardano-node version
      shell: cardano-node --version
      register: cardano_node_version
      changed_when: false
      args:
        chdir: "{{ user_home }}"

    - name: Display cardano-node version
      debug:
        msg: "{{ cardano_node_version.stdout }}"

    - name: Show cardano-cli version
      shell: cardano-cli --version
      register: cardano_cli_version
      changed_when: false
      args:
        chdir: "{{ user_home }}"

    - name: Display cardano-cli version
      debug:
        msg: "{{ cardano_cli_version.stdout }}"
