- name: Update and configure system
  hosts: localhost
  become: yes
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install chrony
      apt:
        name: chrony
        state: present

    - name: Configure chrony
      copy:
        dest: /etc/chrony/chrony.conf
        content: |
          pool time.google.com       iburst minpoll 1 maxpoll 2 maxdelay 0.3 maxsources 3
          pool ntp.ubuntu.com        iburst minpoll 1 maxpoll 2 maxdelay 0.3 maxsources 3
          pool us.pool.ntp.org       iburst minpoll 1 maxpoll 2 maxdelay 0.3 maxsources 3

          keyfile /etc/chrony/chrony.keys
          driftfile /var/lib/chrony/chrony.drift
          #log tracking measurements statistics
          logdir /var/log/chrony
          maxupdateskew 5.0
          rtcsync
          makestep 0.1 -1

    - name: Restart chronyd service
      service:
        name: chronyd
        state: restarted
        enabled: yes

    - name: Set timezone to Europe/London
      timezone:
        name: Europe/London
