- name: 06-blst_Install
  hosts: localhost
  vars_files:
    - ../install_param.yml
  
  tasks:
    - name: Ensure git directory exists
      file:
        path: "{{ user_home }}/git"
        state: directory
        mode: '0755'
    
    - name: Clone blst
      git:
        repo: https://github.com/supranational/blst
        dest: "{{ user_home }}/git/blst"
        version: "{{ blst_version }}"

    - name: Build blst
      shell: ./build.sh >> {{ log_file }} 2>&1
      args:
        chdir: "{{ user_home }}/git/blst"
        executable: /bin/bash
      become: yes

    - name: Create libblst.pc
      copy:
        dest: "{{ user_home }}/git/blst/libblst.pc"
        content: |
          prefix=/usr/local
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib
          includedir=${prefix}/include

          Name: libblst
          Description: Multilingual BLS12-381 signature library
          URL: https://github.com/supranational/blst
          Version: {{ blst_version }}
          Cflags: -I${includedir}
          Libs: -L${libdir} -lblst

    - name: Deploy blst files
      shell: |
        cp libblst.pc /usr/local/lib/pkgconfig/
        cp bindings/blst_aux.h bindings/blst.h bindings/blst.hpp /usr/local/include/
        cp libblst.a /usr/local/lib
        chmod u=rw,go=r /usr/local/{lib/{libblst.a,pkgconfig/libblst.pc},include/{blst.{h,hpp},blst_aux.h}}
      args:
        chdir: "{{ user_home }}/git/blst"
        executable: /bin/bash
      become: yes