- name: Update and configure system
  hosts: localhost
  vars_files:
    - install_param.yml
  
  tasks:
    - name: Append environment variables to .bashrc
      blockinfile:
        path: "{{ user_home }}/.bashrc"
        marker: "# {mark} ANSIBLE-CARDANO-ENV"
        block: |
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export NODE_HOME="$HOME/cardano-my-node"
          export NODE_CONFIG="mainnet"
          export CARDANO_NODE_SOCKET_PATH="$NODE_HOME/db/socket"

    - name: Create Cardano node home directory
      file:
        path: "{{ user_home }}/cardano-my-node"
        state: directory
        mode: '0755'